==============
printfunctions
==============

A python library for easier and more customizable text handling.

Includes printing with a delay in between diffrent characters, printing with color, and using input with a delay.

We ask that major contributers add a statement such as the following to their code at least once, or add it as a comment in a pull request.

``I dedicate any and all copyright interest in this software to the
public domain. I make this dedication for the benefit of the public at
large and to the detriment of my heirs and successors. I intend this
dedication to be an overt act of relinquishment in perpetuity of all
present and future rights to this software under copyright law.``

